spring.application.name=notification-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/securebank?currentSchema=notification_service
spring.datasource.username=securebank
spring.datasource.password=securebank123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=notification_service

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=notification_service
spring.flyway.create-schemas=true

spring.kafka.bootstrap-servers=localhost:9092

management.endpoints.web.exposure.include=health,info